# Generated by Django 4.0.2 on 2022-05-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_message_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(max_length=200),
        ),
    ]
