# Generated by Django 4.0.2 on 2022-05-04 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0010_article_user_article_foreign_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_user',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.folder'),
        ),
    ]
