# Generated by Django 4.0.2 on 2022-04-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile_images'),
        ),
    ]
