# Generated by Django 4.0.2 on 2022-04-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ProfileImage',
            new_name='profile_image',
        ),
    ]
