# Generated by Django 4.0.2 on 2022-04-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0007_article_version_status_alter_article_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='version_status',
            field=models.SmallIntegerField(choices=[(4, 'Active'), (5, 'History'), (6, 'New Version')]),
        ),
    ]
