# Generated by Django 4.0.2 on 2022-04-20 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0008_alter_article_version_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_status',
            new_name='article_status_id',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='version_status',
            new_name='version_status_id',
        ),
    ]
