# Generated by Django 4.0.2 on 2022-05-03 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_rename_profileimage_user_profile_image'),
        ('knowledgebase', '0009_rename_article_status_article_article_status_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='foreign_users',
            field=models.ManyToManyField(related_name='foreign_articles', through='knowledgebase.Article_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article_user',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.article'),
        ),
        migrations.AddField(
            model_name='article_user',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.folder'),
        ),
        migrations.AddField(
            model_name='article_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='article_user',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='unique article_user'),
        ),
    ]
